### ISSUE TITLE
BBS Detail -- > Element

### ISSUE THREAD

**Issue by Mamta123** [tggwlcube/Mesh_India#12]
1. In BBS detail though you are selecting different element, Tag is added in first element always.

**Comment by krishna-ss1** [comment]
Ma'am I've entered a tag with different element. And element id is correctly saved. **Pls see this image attached.** You'll find an element id "2" in between 1.
![element](https://user-images.githubusercontent.com/5309782/28955651-b752fc50-7905-11e7-966f-ca16ec26156c.JPG)
