### ISSUE TITLE
Transaction -> Order details -> Slab BBS Detail -> Add new element

### ISSUE THREAD

**Issue by karantsl** [tggwlcube/Mesh_India#22]
MW length and CW length should include MO1, MO2 & CO1,CO2 respectively which is not the case right now. Also MO1, MO2, CO1 and CO2 values should be flexible.

**Comment by tggwlcube** [comment]
1. MW length and CW length include MO1, MO2 & CO1,CO2 respectively  right now. 

2.  MO1, MO2, CO1 and CO2 values should be flexible.

The flow is as below ;
1. User input MW & CW length (including Overhangs) 
2. While adding dimensions there is option to cahnge Overhangs,so it is flexible. System also suggest combination of MW overhangs & CW overhangs.
3. All calculation is Product Code dependent.

Say, Product Code = A10,
 MW Len= 3000
CW length = 2000
![image](https://user-images.githubusercontent.com/5320397/29351864-31da4e8a-8282-11e7-866f-ec15a5089983.png)
here by default Overhang is 50,50 ...which is editable. If without changing that you press SAVE, system will pop-up message suggesting overhangs.
![image](https://user-images.githubusercontent.com/5320397/29351938-7145057e-8282-11e7-907f-53c760b5a1cf.png)

**Comment by karantsl** [comment]
Overhangs shall be kept flexible without constraints while inputting the value. We are willing to provide overhangs of any length as desired by the customer.

**Comment by tggwlcube** [comment]
there is no constraint Karan...you are free to put any overhang but as suggested by system. coz then only Calculation for No. Of wires can be integer. customer can demand any overhang but if product code is selected then you have to choose from the option. The thing which you are asking,may come in BOM,in which you can play with Spacing and overhang.

**Comment by karantsl** [comment]
Understood this Sir. Thanks
