### ISSUE TITLE
MESH Detailing System

### ISSUE THREAD

**Issue by karantsl** [tggwlcube/Mesh_India#23]
Kindly change the name "BBS" to "Mesh Dimension Detail" or "MDD" everywhere in the system.

**Comment by krishna-ss1** [comment]
"Mesh Dimension Detail" is a bit longer name. "MDD" is good.

**Comment by karantsl** [comment]
MDD is good. Thanks.

**Comment by karantsl** [comment]
<img width="452" alt="mdd" src="https://user-images.githubusercontent.com/30585471/29358931-7d67fa56-829a-11e7-937d-f190e2a2da36.png">
In places like this, write complete "mesh dimension detail", if possible.

**Comment by tggwlcube** [comment]
![image](https://user-images.githubusercontent.com/5320397/29358899-57f21a68-829a-11e7-8648-125f26c953af.png)

Here(Slab BBs Detail) you put "Mesh Dimension Detail"
And in All Linkages Were we have written BBS there you change it to MDD

Remember to add Tool Tip showing "Mesh Dimension Detail" wherever you are using MDD.

**Comment by krishna-ss1** [comment]
Okay..

**Comment by karantsl** [comment]
![image](https://user-images.githubusercontent.com/30585471/29649749-cda1435a-88b3-11e7-8f11-1ff58056cfff.png)

except at the top left corner, BBS to MDD issue is sorted now. Kindly see this and then we will close this issue.

**Comment by krishna-ss1** [comment]
Done

**Comment by tggwlcube** [comment]
karan,Close this one based on BBS changed to MDD etc. For reports image let issue #24 be open

**Comment by karantsl** [comment]
Great. Thanks
