### ISSUE TITLE
Tag print

### ISSUE THREAD

**Issue by karantsl** [tggwlcube/Mesh_India#25]
Kindly see that when tag is exported as pdf file, all tags come on separate pages of the pdf. It would be preferable for them to be on the same page (9-10 tags per page) for cost effective tag printing.

**Comment by tggwlcube** [comment]
Noted. We are working on that. I'll Inform once completed.

**Comment by pratik-ss2** [comment]
Done

**Comment by karantsl** [comment]
Kindly see that in my system, each tag still prints on different pages and not on the same.

**Comment by tggwlcube** [comment]
Karan Please check now.

**Comment by karantsl** [comment]
Perfect. Thank you.
