### ISSUE TITLE
Transaction -> Order detail -> Slab BBS Detail

### ISSUE THREAD

**Issue by karantsl** [tggwlcube/Mesh_India#26]
<img width="630" alt="dddd" src="https://user-images.githubusercontent.com/30585471/29403569-53d6976c-8356-11e7-95c3-0da61b6fdc13.png">

Currently, the print button has to be clicked for entering tag details after the element dimension are entered. Kindly make a separate button for the purpose adjacent to the print button. An illustration can be seen in the snapshot.

**Comment by tggwlcube** [comment]
No Karan, You need to click TAB after selecting Shape ID. No need to click on print button. System was designed keeping into mind that operators are least interested in using mouse. So all entry are on TAB. Try using TAB and let me know if there any problem.

after each entry press TAB like enter MW length Then press TAB..likewise fill all input fields...and after entering Shape Id press TAB.

**Comment by karantsl** [comment]
Ok. This seems fine then.
