### ISSUE TITLE
Masters -> Product details

### ISSUE THREAD

**Issue by karantsl** [tggwlcube/Mesh_India#30]
![image](https://user-images.githubusercontent.com/30585471/29605198-a07a7682-8807-11e7-94d8-5aee52d0d5da.png)

Just an observation, Kindly keep the letter "a" etc. in capital.

**Comment by tggwlcube** [comment]
Product Code Updated. Please check.

**Comment by karantsl** [comment]
This looks good. Thanks. Closing the issue.

**Comment by tggwlcube** [comment]
Please try to add one by yourself, and let me know incase of any issue. You can delete it later.

**Comment by karantsl** [comment]
Works fine. Tried to add one.
