### ISSUE TITLE
Masters - > Grade detail

### ISSUE THREAD

**Issue by karantsl** [tggwlcube/Mesh_India#31]
![image](https://user-images.githubusercontent.com/30585471/29613920-b6b48762-8825-11e7-8787-a5bc92ab818d.png)

Kindly note that the first two are "Wire Rod" and not Mesh.

**Comment by tggwlcube** [comment]
Actually we used this field "Product Type"to differentiate between CAB & Mesh . We had one system for Cut & Bend and MESH in Xiamen. But Let me think if we can use this as suggested by you. 

In Material Where there is Bar Type we can change that into Wire Rod Type. Please suggest

**Comment by karantsl** [comment]
Yes, can be done. Also try to make product type "Wire Rod" here too as is suggested by Rameshwar Sir.

**Comment by tggwlcube** [comment]
Done
