### ISSUE TITLE
Mesh dimension detail 

### ISSUE THREAD

**Issue by karantsl** [tggwlcube/Mesh_India#32]
![image](https://user-images.githubusercontent.com/30585471/29649621-d8fa1f3e-88b2-11e7-9cb8-2cf9d6234f0f.png)

While saving the dimensions, this pop up appears. Kindly check.

**Comment by tggwlcube** [comment]
You have selected Diameter 6. Wherein In Material Master for this Grade only diameter 8 has been added.
![image](https://user-images.githubusercontent.com/5320397/29649730-a63e73e6-88b3-11e7-985a-ed62b5c85049.png)

**Comment by tggwlcube** [comment]
either change diameter to 8 or Add dimeter 6 in that grade by following these steps:-

1. Master-->Grade Detail --(Go to the row in which you need to add)
2.  Left Side there is menu strip (The very first column in which you can see 4 horizontal lines)
3. Click on that-->There is a linkage "View Dia"-- Click on "View Dia"
4. Right side new grid will be populated.
5. Above right grid there is plus sign. Add the new diameter And SAVe.

**Comment by karantsl** [comment]
Ok thanks. Works well
